### ISSUE TITLE
player toolbar don't fit in the screen

### ISSUE THREAD

**Issue by tempral** [ditek/MidiSheetMusic-Android#15]
app/src/main/res/layout/player_toolbar.xml

the toolbar is too long that don't display entirely on my Huawei p8 lite 2017 android 8.0
the last UI button that I can press is the R channel toggle.

so probably the same problem could occur on many devices

**Comment by ditek** [comment]
Thanks for reporting. It would be helpful if you could attach a screenshot
of that.

fre. 8. nov. 2019, 12:25 skrev Carmine Zonno <notifications@github.com>:

**Comment by tempral** [comment]
i built the source and made the speed bar shorter to let enter on the screen the lasts Ui buttons,
later I'll put back the width size of that element and take a screenshot

**Comment by ditek** [comment]
Fixed in a proper way. Sorry it took too long.
Please reopen if the issue persists.
