### ISSUE TITLE
Where to find the APK?

### ISSUE THREAD

**Issue by IzzySoft** [ditek/MidiSheetMusic-Android#6]
Would you mind [tagging](https://github.com/ditek/MidiSheetMusic-Android/releases) your releases and attaching the APK to its related tag, so "normal users" (who cannot build themselves) can have access to it? Or have it listed on F-Droid?

**Comment by ditek** [comment]
Thanks for your interest in the project.
Currently, the project is still in development and it has not been released yet.

**Comment by IzzySoft** [comment]
Ah, that explains, thanks! I hope you don't mind leaving this issue open and closing it when an APK is available (or you want the app added to F-Droid), to trigger a notice then?

**Comment by ditek** [comment]
I'd rather close this for now so I can better focus on actual application issues.
I will put a link to the app store once it's available.
Thanks for understanding.

**Comment by IzzySoft** [comment]
@ditek looks like there's a little misunderstanding: I wasn't asking for an app store but for the APK file itself or a listing at F-Droid (which I could assist you with; a.o. for privacy reasons, I (and many others) don't use Playstore, just F-Droid). Also, I won't get a notice if you put a link on the readme (but of course I will if you put it here). So I hope you remember mentioning it here when available, even though this issue is already closed :wink:

All the best for your project!
